// GENERATED by tools/build-icons.ts from resources/designsystem/.
// DO NOT EDIT. Run `pnpm icons:build` and commit the result.
//
// HERO_ICONS is Record<HeroId, string> over the 27-id literal union, so a hero
// without an icon is a COMPILE ERROR rather than a blank square (FR-010).

import type { HeroId } from '@lmntlz/content';

import heroEarthBramwen from '../../assets/icons/hero/earth-bramwen.svg';
import heroEarthOssic from '../../assets/icons/hero/earth-ossic.svg';
import heroEarthTerragosa from '../../assets/icons/hero/earth-terragosa.svg';
import heroAirZephyrine from '../../assets/icons/hero/air-zephyrine.svg';
import heroAirCirrolan from '../../assets/icons/hero/air-cirrolan.svg';
import heroAirVael from '../../assets/icons/hero/air-vael.svg';
import heroFireEmberSaelith from '../../assets/icons/hero/fire-ember-saelith.svg';
import heroFirePyrrhic from '../../assets/icons/hero/fire-pyrrhic.svg';
import heroFireCindara from '../../assets/icons/hero/fire-cindara.svg';
import heroWaterMarisel from '../../assets/icons/hero/water-marisel.svg';
import heroWaterTidewardenColl from '../../assets/icons/hero/water-tidewarden-coll.svg';
import heroWaterNix from '../../assets/icons/hero/water-nix.svg';
import heroLightSeraphel from '../../assets/icons/hero/light-seraphel.svg';
import heroLightLucen from '../../assets/icons/hero/light-lucen.svg';
import heroLightAurielDawnkeep from '../../assets/icons/hero/light-auriel-dawnkeep.svg';
import heroDarkNyxara from '../../assets/icons/hero/dark-nyxara.svg';
import heroDarkUmbriel from '../../assets/icons/hero/dark-umbriel.svg';
import heroDarkCorvane from '../../assets/icons/hero/dark-corvane.svg';
import heroSlashKaellis from '../../assets/icons/hero/slash-kaellis.svg';
import heroSlashReyna from '../../assets/icons/hero/slash-reyna.svg';
import heroSlashGrieve from '../../assets/icons/hero/slash-grieve.svg';
import heroPierceVantric from '../../assets/icons/hero/pierce-vantric.svg';
import heroPierceSilka from '../../assets/icons/hero/pierce-silka.svg';
import heroPierceAiguille from '../../assets/icons/hero/pierce-aiguille.svg';
import heroCrushBoldrek from '../../assets/icons/hero/crush-boldrek.svg';
import heroCrushHettamar from '../../assets/icons/hero/crush-hettamar.svg';
import heroCrushMauless from '../../assets/icons/hero/crush-mauless.svg';

import statusOverlaySealed from '../../assets/icons/status/overlay-sealed.svg';
import statusOverlayStack from '../../assets/icons/status/overlay-stack.svg';
import statusPipDotAir from '../../assets/icons/status/pip-dot-air.svg';
import statusPipDotCrush from '../../assets/icons/status/pip-dot-crush.svg';
import statusPipDotDark from '../../assets/icons/status/pip-dot-dark.svg';
import statusPipDotEarth from '../../assets/icons/status/pip-dot-earth.svg';
import statusPipDotFire from '../../assets/icons/status/pip-dot-fire.svg';
import statusPipDotLight from '../../assets/icons/status/pip-dot-light.svg';
import statusPipDotPierce from '../../assets/icons/status/pip-dot-pierce.svg';
import statusPipDotSlash from '../../assets/icons/status/pip-dot-slash.svg';
import statusPipDotWater from '../../assets/icons/status/pip-dot-water.svg';
import statusPipExposed from '../../assets/icons/status/pip-exposed.svg';
import statusPipExtendedReach from '../../assets/icons/status/pip-extended-reach.svg';
import statusPipFade from '../../assets/icons/status/pip-fade.svg';
import statusPipRenewed from '../../assets/icons/status/pip-renewed.svg';
import statusPipReprisal from '../../assets/icons/status/pip-reprisal.svg';
import statusPipRooted from '../../assets/icons/status/pip-rooted.svg';
import statusPipShield from '../../assets/icons/status/pip-shield.svg';
import statusPipSilence from '../../assets/icons/status/pip-silence.svg';
import statusPipStatAgilityDown from '../../assets/icons/status/pip-stat-agility-down.svg';
import statusPipStatAgilityUp from '../../assets/icons/status/pip-stat-agility-up.svg';
import statusPipStatArmorDown from '../../assets/icons/status/pip-stat-armor-down.svg';
import statusPipStatArmorUp from '../../assets/icons/status/pip-stat-armor-up.svg';
import statusPipStatLuckDown from '../../assets/icons/status/pip-stat-luck-down.svg';
import statusPipStatLuckUp from '../../assets/icons/status/pip-stat-luck-up.svg';
import statusPipStatMightDown from '../../assets/icons/status/pip-stat-might-down.svg';
import statusPipStatMightUp from '../../assets/icons/status/pip-stat-might-up.svg';
import statusPipStatPenetrationDown from '../../assets/icons/status/pip-stat-penetration-down.svg';
import statusPipStatPenetrationUp from '../../assets/icons/status/pip-stat-penetration-up.svg';
import statusPipStatPerceptionDown from '../../assets/icons/status/pip-stat-perception-down.svg';
import statusPipStatPerceptionUp from '../../assets/icons/status/pip-stat-perception-up.svg';
import statusPipStatResistDown from '../../assets/icons/status/pip-stat-resist-down.svg';
import statusPipStatResistUp from '../../assets/icons/status/pip-stat-resist-up.svg';
import statusPipStatResolveDown from '../../assets/icons/status/pip-stat-resolve-down.svg';
import statusPipStatResolveUp from '../../assets/icons/status/pip-stat-resolve-up.svg';
import statusPipStatSpeedDown from '../../assets/icons/status/pip-stat-speed-down.svg';
import statusPipStatSpeedUp from '../../assets/icons/status/pip-stat-speed-up.svg';
import statusPipStatToughnessDown from '../../assets/icons/status/pip-stat-toughness-down.svg';
import statusPipStatToughnessUp from '../../assets/icons/status/pip-stat-toughness-up.svg';
import statusPipStun from '../../assets/icons/status/pip-stun.svg';
import statusPipTaunt from '../../assets/icons/status/pip-taunt.svg';
import statusPipUnbreakable from '../../assets/icons/status/pip-unbreakable.svg';
import statusPipUnseen from '../../assets/icons/status/pip-unseen.svg';
import statusPipWarded from '../../assets/icons/status/pip-warded.svg';
import statusPipWithered from '../../assets/icons/status/pip-withered.svg';
import statusStatusDot from '../../assets/icons/status/status-dot.svg';
import statusStatusExposed from '../../assets/icons/status/status-exposed.svg';
import statusStatusExtendedReach from '../../assets/icons/status/status-extended-reach.svg';
import statusStatusFade from '../../assets/icons/status/status-fade.svg';
import statusStatusRenewed from '../../assets/icons/status/status-renewed.svg';
import statusStatusReprisal from '../../assets/icons/status/status-reprisal.svg';
import statusStatusRooted from '../../assets/icons/status/status-rooted.svg';
import statusStatusSealed from '../../assets/icons/status/status-sealed.svg';
import statusStatusShield from '../../assets/icons/status/status-shield.svg';
import statusStatusSilence from '../../assets/icons/status/status-silence.svg';
import statusStatusStatAgility from '../../assets/icons/status/status-stat-agility.svg';
import statusStatusStatArmor from '../../assets/icons/status/status-stat-armor.svg';
import statusStatusStatLuck from '../../assets/icons/status/status-stat-luck.svg';
import statusStatusStatMight from '../../assets/icons/status/status-stat-might.svg';
import statusStatusStatPenetration from '../../assets/icons/status/status-stat-penetration.svg';
import statusStatusStatPerception from '../../assets/icons/status/status-stat-perception.svg';
import statusStatusStatResist from '../../assets/icons/status/status-stat-resist.svg';
import statusStatusStatResolve from '../../assets/icons/status/status-stat-resolve.svg';
import statusStatusStatSpeed from '../../assets/icons/status/status-stat-speed.svg';
import statusStatusStatToughness from '../../assets/icons/status/status-stat-toughness.svg';
import statusStatusStun from '../../assets/icons/status/status-stun.svg';
import statusStatusTaunt from '../../assets/icons/status/status-taunt.svg';
import statusStatusUnbreakable from '../../assets/icons/status/status-unbreakable.svg';
import statusStatusUnseen from '../../assets/icons/status/status-unseen.svg';
import statusStatusWarded from '../../assets/icons/status/status-warded.svg';
import statusStatusWithered from '../../assets/icons/status/status-withered.svg';

export const HERO_ICONS: Record<HeroId, string> = {
  h01: heroEarthBramwen,
  h02: heroEarthOssic,
  h03: heroEarthTerragosa,
  h04: heroAirZephyrine,
  h05: heroAirCirrolan,
  h06: heroAirVael,
  h07: heroFireEmberSaelith,
  h08: heroFirePyrrhic,
  h09: heroFireCindara,
  h10: heroWaterMarisel,
  h11: heroWaterTidewardenColl,
  h12: heroWaterNix,
  h13: heroLightSeraphel,
  h14: heroLightLucen,
  h15: heroLightAurielDawnkeep,
  h16: heroDarkNyxara,
  h17: heroDarkUmbriel,
  h18: heroDarkCorvane,
  h19: heroSlashKaellis,
  h20: heroSlashReyna,
  h21: heroSlashGrieve,
  h22: heroPierceVantric,
  h23: heroPierceSilka,
  h24: heroPierceAiguille,
  h25: heroCrushBoldrek,
  h26: heroCrushHettamar,
  h27: heroCrushMauless,
};

export const STATUS_ICON_KEYS = Object.freeze([
  'overlay-sealed',
  'overlay-stack',
  'pip-dot-air',
  'pip-dot-crush',
  'pip-dot-dark',
  'pip-dot-earth',
  'pip-dot-fire',
  'pip-dot-light',
  'pip-dot-pierce',
  'pip-dot-slash',
  'pip-dot-water',
  'pip-exposed',
  'pip-extended-reach',
  'pip-fade',
  'pip-renewed',
  'pip-reprisal',
  'pip-rooted',
  'pip-shield',
  'pip-silence',
  'pip-stat-agility-down',
  'pip-stat-agility-up',
  'pip-stat-armor-down',
  'pip-stat-armor-up',
  'pip-stat-luck-down',
  'pip-stat-luck-up',
  'pip-stat-might-down',
  'pip-stat-might-up',
  'pip-stat-penetration-down',
  'pip-stat-penetration-up',
  'pip-stat-perception-down',
  'pip-stat-perception-up',
  'pip-stat-resist-down',
  'pip-stat-resist-up',
  'pip-stat-resolve-down',
  'pip-stat-resolve-up',
  'pip-stat-speed-down',
  'pip-stat-speed-up',
  'pip-stat-toughness-down',
  'pip-stat-toughness-up',
  'pip-stun',
  'pip-taunt',
  'pip-unbreakable',
  'pip-unseen',
  'pip-warded',
  'pip-withered',
  'status-dot',
  'status-exposed',
  'status-extended-reach',
  'status-fade',
  'status-renewed',
  'status-reprisal',
  'status-rooted',
  'status-sealed',
  'status-shield',
  'status-silence',
  'status-stat-agility',
  'status-stat-armor',
  'status-stat-luck',
  'status-stat-might',
  'status-stat-penetration',
  'status-stat-perception',
  'status-stat-resist',
  'status-stat-resolve',
  'status-stat-speed',
  'status-stat-toughness',
  'status-stun',
  'status-taunt',
  'status-unbreakable',
  'status-unseen',
  'status-warded',
  'status-withered',
] as const);

export type StatusIconKey = (typeof STATUS_ICON_KEYS)[number];

export const STATUS_ICONS: Record<StatusIconKey, string> = {
  'overlay-sealed': statusOverlaySealed,
  'overlay-stack': statusOverlayStack,
  'pip-dot-air': statusPipDotAir,
  'pip-dot-crush': statusPipDotCrush,
  'pip-dot-dark': statusPipDotDark,
  'pip-dot-earth': statusPipDotEarth,
  'pip-dot-fire': statusPipDotFire,
  'pip-dot-light': statusPipDotLight,
  'pip-dot-pierce': statusPipDotPierce,
  'pip-dot-slash': statusPipDotSlash,
  'pip-dot-water': statusPipDotWater,
  'pip-exposed': statusPipExposed,
  'pip-extended-reach': statusPipExtendedReach,
  'pip-fade': statusPipFade,
  'pip-renewed': statusPipRenewed,
  'pip-reprisal': statusPipReprisal,
  'pip-rooted': statusPipRooted,
  'pip-shield': statusPipShield,
  'pip-silence': statusPipSilence,
  'pip-stat-agility-down': statusPipStatAgilityDown,
  'pip-stat-agility-up': statusPipStatAgilityUp,
  'pip-stat-armor-down': statusPipStatArmorDown,
  'pip-stat-armor-up': statusPipStatArmorUp,
  'pip-stat-luck-down': statusPipStatLuckDown,
  'pip-stat-luck-up': statusPipStatLuckUp,
  'pip-stat-might-down': statusPipStatMightDown,
  'pip-stat-might-up': statusPipStatMightUp,
  'pip-stat-penetration-down': statusPipStatPenetrationDown,
  'pip-stat-penetration-up': statusPipStatPenetrationUp,
  'pip-stat-perception-down': statusPipStatPerceptionDown,
  'pip-stat-perception-up': statusPipStatPerceptionUp,
  'pip-stat-resist-down': statusPipStatResistDown,
  'pip-stat-resist-up': statusPipStatResistUp,
  'pip-stat-resolve-down': statusPipStatResolveDown,
  'pip-stat-resolve-up': statusPipStatResolveUp,
  'pip-stat-speed-down': statusPipStatSpeedDown,
  'pip-stat-speed-up': statusPipStatSpeedUp,
  'pip-stat-toughness-down': statusPipStatToughnessDown,
  'pip-stat-toughness-up': statusPipStatToughnessUp,
  'pip-stun': statusPipStun,
  'pip-taunt': statusPipTaunt,
  'pip-unbreakable': statusPipUnbreakable,
  'pip-unseen': statusPipUnseen,
  'pip-warded': statusPipWarded,
  'pip-withered': statusPipWithered,
  'status-dot': statusStatusDot,
  'status-exposed': statusStatusExposed,
  'status-extended-reach': statusStatusExtendedReach,
  'status-fade': statusStatusFade,
  'status-renewed': statusStatusRenewed,
  'status-reprisal': statusStatusReprisal,
  'status-rooted': statusStatusRooted,
  'status-sealed': statusStatusSealed,
  'status-shield': statusStatusShield,
  'status-silence': statusStatusSilence,
  'status-stat-agility': statusStatusStatAgility,
  'status-stat-armor': statusStatusStatArmor,
  'status-stat-luck': statusStatusStatLuck,
  'status-stat-might': statusStatusStatMight,
  'status-stat-penetration': statusStatusStatPenetration,
  'status-stat-perception': statusStatusStatPerception,
  'status-stat-resist': statusStatusStatResist,
  'status-stat-resolve': statusStatusStatResolve,
  'status-stat-speed': statusStatusStatSpeed,
  'status-stat-toughness': statusStatusStatToughness,
  'status-stun': statusStatusStun,
  'status-taunt': statusStatusTaunt,
  'status-unbreakable': statusStatusUnbreakable,
  'status-unseen': statusStatusUnseen,
  'status-warded': statusStatusWarded,
  'status-withered': statusStatusWithered,
};
