// GENERATED by tools/build-content.ts from resources/characters/hero-stats.xlsx.
// DO NOT EDIT. Run `pnpm content:build` and commit the result.
//
// Constitution XV: bane, fault, strengths and family are DERIVED here and are
// not authored anywhere. Editing this file by hand would make the roster and its
// source disagree, and CI diffs it against a fresh build precisely to catch that.

/** `"c" + sha256(workbook bytes)[0:12]`. Distinct from engineVersion. */
export const CONTENT_VERSION = 'c0f64f2490b78';
