// GENERATED by tools/build-portraits.py from resources/design/images/.
// DO NOT EDIT. Run `pnpm portraits:build` and commit the result.
//
// HERO_PORTRAITS is Record<HeroId, HeroPortraitSources> over the 27-id
// literal union, so a hero without art is a COMPILE ERROR rather than a
// blank card -- the same guarantee HERO_ICONS gives.

import type { HeroId } from '@lmntlz/content';

import portraitEarthBramwen240 from '../../assets/portraits/earth-bramwen-240.webp';
import portraitEarthBramwen480 from '../../assets/portraits/earth-bramwen-480.webp';
import portraitEarthOssic240 from '../../assets/portraits/earth-ossic-240.webp';
import portraitEarthOssic480 from '../../assets/portraits/earth-ossic-480.webp';
import portraitEarthTerragosa240 from '../../assets/portraits/earth-terragosa-240.webp';
import portraitEarthTerragosa480 from '../../assets/portraits/earth-terragosa-480.webp';
import portraitAirZephyrine240 from '../../assets/portraits/air-zephyrine-240.webp';
import portraitAirZephyrine480 from '../../assets/portraits/air-zephyrine-480.webp';
import portraitAirCirrolan240 from '../../assets/portraits/air-cirrolan-240.webp';
import portraitAirCirrolan480 from '../../assets/portraits/air-cirrolan-480.webp';
import portraitAirVael240 from '../../assets/portraits/air-vael-240.webp';
import portraitAirVael480 from '../../assets/portraits/air-vael-480.webp';
import portraitFireEmberSaelith240 from '../../assets/portraits/fire-ember-saelith-240.webp';
import portraitFireEmberSaelith480 from '../../assets/portraits/fire-ember-saelith-480.webp';
import portraitFirePyrrhic240 from '../../assets/portraits/fire-pyrrhic-240.webp';
import portraitFirePyrrhic480 from '../../assets/portraits/fire-pyrrhic-480.webp';
import portraitFireCindara240 from '../../assets/portraits/fire-cindara-240.webp';
import portraitFireCindara480 from '../../assets/portraits/fire-cindara-480.webp';
import portraitWaterMarisel240 from '../../assets/portraits/water-marisel-240.webp';
import portraitWaterMarisel480 from '../../assets/portraits/water-marisel-480.webp';
import portraitWaterTidewardenColl240 from '../../assets/portraits/water-tidewarden-coll-240.webp';
import portraitWaterTidewardenColl480 from '../../assets/portraits/water-tidewarden-coll-480.webp';
import portraitWaterNix240 from '../../assets/portraits/water-nix-240.webp';
import portraitWaterNix480 from '../../assets/portraits/water-nix-480.webp';
import portraitLightSeraphel240 from '../../assets/portraits/light-seraphel-240.webp';
import portraitLightSeraphel480 from '../../assets/portraits/light-seraphel-480.webp';
import portraitLightLucen240 from '../../assets/portraits/light-lucen-240.webp';
import portraitLightLucen480 from '../../assets/portraits/light-lucen-480.webp';
import portraitLightAurielDawnkeep240 from '../../assets/portraits/light-auriel-dawnkeep-240.webp';
import portraitLightAurielDawnkeep480 from '../../assets/portraits/light-auriel-dawnkeep-480.webp';
import portraitDarkNyxara240 from '../../assets/portraits/dark-nyxara-240.webp';
import portraitDarkNyxara480 from '../../assets/portraits/dark-nyxara-480.webp';
import portraitDarkUmbriel240 from '../../assets/portraits/dark-umbriel-240.webp';
import portraitDarkUmbriel480 from '../../assets/portraits/dark-umbriel-480.webp';
import portraitDarkCorvane240 from '../../assets/portraits/dark-corvane-240.webp';
import portraitDarkCorvane480 from '../../assets/portraits/dark-corvane-480.webp';
import portraitSlashKaellis240 from '../../assets/portraits/slash-kaellis-240.webp';
import portraitSlashKaellis480 from '../../assets/portraits/slash-kaellis-480.webp';
import portraitSlashReyna240 from '../../assets/portraits/slash-reyna-240.webp';
import portraitSlashReyna480 from '../../assets/portraits/slash-reyna-480.webp';
import portraitSlashGrieve240 from '../../assets/portraits/slash-grieve-240.webp';
import portraitSlashGrieve480 from '../../assets/portraits/slash-grieve-480.webp';
import portraitPierceVantric240 from '../../assets/portraits/pierce-vantric-240.webp';
import portraitPierceVantric480 from '../../assets/portraits/pierce-vantric-480.webp';
import portraitPierceSilka240 from '../../assets/portraits/pierce-silka-240.webp';
import portraitPierceSilka480 from '../../assets/portraits/pierce-silka-480.webp';
import portraitPierceAiguille240 from '../../assets/portraits/pierce-aiguille-240.webp';
import portraitPierceAiguille480 from '../../assets/portraits/pierce-aiguille-480.webp';
import portraitCrushBoldrek240 from '../../assets/portraits/crush-boldrek-240.webp';
import portraitCrushBoldrek480 from '../../assets/portraits/crush-boldrek-480.webp';
import portraitCrushHettamar240 from '../../assets/portraits/crush-hettamar-240.webp';
import portraitCrushHettamar480 from '../../assets/portraits/crush-hettamar-480.webp';
import portraitCrushMauless240 from '../../assets/portraits/crush-mauless-240.webp';
import portraitCrushMauless480 from '../../assets/portraits/crush-mauless-480.webp';

/** One hero's art at the two widths the screens actually request. */
export interface HeroPortraitSources {
  readonly w240: string;
  readonly w480: string;
}

/** The intrinsic aspect ratio of every portrait, for `aspect-*` and CLS. */
export const PORTRAIT_ASPECT = Object.freeze({ width: 948, height: 1659 });

export const HERO_PORTRAITS: Record<HeroId, HeroPortraitSources> = {
  h01: { w240: portraitEarthBramwen240, w480: portraitEarthBramwen480 },
  h02: { w240: portraitEarthOssic240, w480: portraitEarthOssic480 },
  h03: { w240: portraitEarthTerragosa240, w480: portraitEarthTerragosa480 },
  h04: { w240: portraitAirZephyrine240, w480: portraitAirZephyrine480 },
  h05: { w240: portraitAirCirrolan240, w480: portraitAirCirrolan480 },
  h06: { w240: portraitAirVael240, w480: portraitAirVael480 },
  h07: { w240: portraitFireEmberSaelith240, w480: portraitFireEmberSaelith480 },
  h08: { w240: portraitFirePyrrhic240, w480: portraitFirePyrrhic480 },
  h09: { w240: portraitFireCindara240, w480: portraitFireCindara480 },
  h10: { w240: portraitWaterMarisel240, w480: portraitWaterMarisel480 },
  h11: { w240: portraitWaterTidewardenColl240, w480: portraitWaterTidewardenColl480 },
  h12: { w240: portraitWaterNix240, w480: portraitWaterNix480 },
  h13: { w240: portraitLightSeraphel240, w480: portraitLightSeraphel480 },
  h14: { w240: portraitLightLucen240, w480: portraitLightLucen480 },
  h15: { w240: portraitLightAurielDawnkeep240, w480: portraitLightAurielDawnkeep480 },
  h16: { w240: portraitDarkNyxara240, w480: portraitDarkNyxara480 },
  h17: { w240: portraitDarkUmbriel240, w480: portraitDarkUmbriel480 },
  h18: { w240: portraitDarkCorvane240, w480: portraitDarkCorvane480 },
  h19: { w240: portraitSlashKaellis240, w480: portraitSlashKaellis480 },
  h20: { w240: portraitSlashReyna240, w480: portraitSlashReyna480 },
  h21: { w240: portraitSlashGrieve240, w480: portraitSlashGrieve480 },
  h22: { w240: portraitPierceVantric240, w480: portraitPierceVantric480 },
  h23: { w240: portraitPierceSilka240, w480: portraitPierceSilka480 },
  h24: { w240: portraitPierceAiguille240, w480: portraitPierceAiguille480 },
  h25: { w240: portraitCrushBoldrek240, w480: portraitCrushBoldrek480 },
  h26: { w240: portraitCrushHettamar240, w480: portraitCrushHettamar480 },
  h27: { w240: portraitCrushMauless240, w480: portraitCrushMauless480 },
};
